#
# Travis CI config for LibreSignage.
#

# Ubuntu Xenial is used to get access to a newer version of GNU Make.
dist: xenial

language: php
php:
    - '7.2'
node_js:
    - "stable"

services:
    - docker

sudo: required

git:
    depth: false

branches:
    only:
        - master
        - next
        - /v[0-9]+.x.x/
        - /v[0-9]+.[0-9]+.[0-9]+/

matrix:
    include:
        - env: target="apache2-debian-docker" opts="--feature-imgthumbs"

install:
    # Install pandoc 2.7.2 from a .deb package because the
    # version in the repos is too old.
    - |
      wget -qO pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
      sudo dpkg -i pandoc.deb
      rm pandoc.deb

    # Install other dependencies from repos & npm.
    - sudo apt-get update
    - sudo apt-get install -y imagemagick composer php-xml

before_script:
    # Configure the build
    - make configure TARGET="$target" PASS="$opts"

script:
    # Build and install
    - make -j$(nproc) && sudo make install

after_success:
    - |
      # Run tests with apache2-debian-docker.
      if [ "$target" = "apache2-debian-docker" ]; then
          tag="$(sudo docker image ls|grep libresignage|head -n1|tr -s ' '|cut -d ' ' -f2)"
          sudo docker run -d -p80:80 "libresignage:$tag"
          make test-api
          sudo docker stop $(sudo docker ps -a -q)
      fi

deploy:
    - provider: script
      script: sh build/scripts/travis/docker_push.sh eerotal nightly
      on:
          branch: next
          condition: $target = 'apache2-debian-docker'
          condition: $TRAVIS_EVENT_TYPE = 'cron'
    - provider: script
      script: sh build/scripts/travis/docker_push.sh eerotal release
      on:
          tags: true
          condition: $target = 'apache2-debian-docker'
